version: '3'
services:
    app:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
      - type: volume
        source: mycred
        target: /root/.local/share/signal-cli/data/
      - .:/app/
      # command: /bin/sh -c "while sleep 1000; do :; done"
      command: /bin/sh -c "while sleep 1000; do :; done"
    
    selenium:
      hostname: selenium
      image:  selenium/standalone-chrome
      ports:
      - 4444:4444
      volumes:
      - /dev/shm:/dev/shm
      environment:
      - SE_NODE_SESSION_TIMEOUT=2628000
  
volumes:
  mycred:
