line-length = 88

# Enable Pyflakes and pycodestyle rules.
select = ["E", "F", "Q"]

# Never enforce `E501` (line length violations).
# ignore = ["E501"]

# Always autofix, but never try to fix `F401` (unused imports).
# fix = true
# unfixable = ["F401"]

[per-file-ignores]
"__init__.py" = ["F401"]
"bot.py" = ["E402", "F401"]
"test_commands.py" = ["E402", "F401"]
