name: Python Checker

on: push

env:
  PYTHON_VERSION: 3.11

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: '${{ env.PYTHON_VERSION }}'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test/requirements.txt
      - name: Analysing code with pylint
        run: |
          pylint $(git ls-files '*.py')
        continue-on-error: true
      - name: Run test codes with pytest
        run: |
          pytest $(git ls-files 'test/*.py')
        continue-on-error: true