name: Python Checker

on: [push]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test/requirements.txt
      - name: Analysing code with pylint
        run: |
          pylint $(git ls-file '*.py')
      - name: Run test codes with pytest
        run: |
          pytest $(git ls-file 'test/*.py')